### ISSUE TITLE
Error when trying to deploy

### ISSUE THREAD

**Issue by tarek-eg** [lastmjs/extendable-token-typescript#2]
Hey,
Following the README and when executing `dfx deploy` I get this error:
```
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "faucet"...
"faucet" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "jsonic"...
"jsonic" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing 'node_modules/.bin/azle jsonic'
    Updating git repository `https://github.com/dfinity/candid.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `candid`

Caused by:
  Unable to update https://github.com/dfinity/candid.git?branch=nat-visitor

Caused by:
  failed to find branch `nat-visitor`

Caused by:
  cannot locate remote-tracking branch 'origin/nat-visitor'; class=Reference (4); code=NotFound (-3)
Error: Command failed: cargo build --target wasm32-unknown-unknown --package jsonic --release
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at compileRustCode (/Users/dev/extendable-token-typescript/node_modules/azle/src/app.ts:123:13)
    at app (/Users/dev/extendable-token-typescript/node_modules/azle/src/app.ts:38:5)
    at Object.<anonymous> (/Users/dev/extendable-token-typescriptnode_modules/azle/src/app.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/Users/dev/extendable-token-typescript/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/dev/extendable-token-typescript/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  status: 101,
  signal: null,
  output: [ null, null, null ],
  pid: 87897,
  stdout: null,
  stderr: null
}
```
On Macbook pro
OS: Macos Monterey
12.0.1
```
➜ dfx --version
dfx 0.8.4
```

```
➜ cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)
```

```
➜ node -v
v14.18.1
```

**Comment by lastmjs** [comment]
Try using azle 0.0.4, edit the main package.json

**Comment by tarek-eg** [comment]
Thanks, that solved the issue
